name: Scala CI

on:
  push:
    branches: [ main]
    tags:
      - "v*"
  pull_request:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@v3
      - run: mkdir -p $HOME/.gnupg/
      - run: echo $PGP_SECRET | base64 -d > $HOME/.gnupg/secring.gpg
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
      - run: export PGP_PUBLIC=$(gpg --armor --export $LONG_ID | base64)
        env:
          PGP_PUBLIC: ${{ secrets.PGP_PUBLIC }}
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - run: sbt release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - run: ls -al ./target