name: Scala CI

on:
  push:
    branches: [ main, setup_release]
  pull_request:
    branches: [ main, setup_release]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run publish
      run: sbt publish
