name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: SBT Action
        env:
          JAVA_VERSIONS: "8"
          SBT_VERSIONS: "1.3.0"
          SCALA_VERSIONS: "2.13.0"
        uses: lokkju/github-action-sbt@v0.2.2
          with:
            commands: publish